blank_issues_enabled: false
contact_links:
  - name: Mapillary Community Forum
    url: https://forum.mapillary.com/t/introducing-a-mapillary-arcgis-experience-builder-integration-widget-mapillary-explorer/10013
    about: For general Mapillary coverage and imagery questions, the forum is the best place to ask.
  - name: ArcGIS Experience Builder Community
    url: https://community.esri.com/t5/experience-builder-custom-widgets/mapillary-explorer-a-custom-arcgis-experience/td-p/1690986
    about: For questions specific to ArcGIS Experience Builder setup and configuration.
