// A lookup table for Mapillary object classification labels
// Exported as a named constant.

export const objectNameMap: Record<string, string> = {
    "construction--barrier--temporary": "Temporary Barrier",
    "construction--flat--crosswalk-plain": "Crosswalk - Plain",
    "construction--flat--driveway": "Driveway",
    "marking--discrete--arrow--left": "Lane Marking - Arrow (Left)",
    "marking--discrete--arrow--right": "Lane Marking - Arrow (Right)",
    "marking--discrete--arrow--split-left-or-straight": "Lane Marking - Arrow (Split Left or Straight)",
    "marking--discrete--arrow--split-right-or-straight": "Lane Marking - Arrow (Split Right or Straight)",
    "marking--discrete--arrow--straight": "Lane Marking - Arrow (Straight)",
    "marking--discrete--crosswalk-zebra": "Lane Marking - Crosswalk",
    "marking--discrete--give-way-row": "Lane Marking - Give Way (Row)",
    "marking--discrete--give-way-single": "Lane Marking - Give Way (Single)",
    "marking--discrete--other-marking": "Lane Marking - Other",
    "marking--discrete--stop-line": "Lane Marking - Stop Line",
    "marking--discrete--symbol--bicycle": "Lane Marking - Symbol (Bicycle)",
    "marking--discrete--text": "Lane Marking - Text",
    "object--banner": "Banner",
    "object--bench": "Bench",
    "object--bike-rack": "Bike Rack",
    "object--catch-basin": "Catch Basin",
    "object--cctv-camera": "CCTV Camera",
    "object--fire-hydrant": "Fire Hydrant",
    "object--junction-box": "Junction Box",
    "object--mailbox": "Mailbox",
    "object--manhole": "Manhole",
    "object--parking-meter": "Parking Meter",
    "object--phone-booth": "Phone Booth",
    "object--sign--advertisement": "Signage - Advertisement",
    "object--sign--information": "Signage - Information",
    "object--sign--store": "Signage - Store",
    "object--street-light": "Street Light",
    "object--support--pole": "Pole",
    "object--support--traffic-sign-frame": "Traffic Sign Frame",
    "object--support--utility-pole": "Utility Pole",
    "object--traffic-cone": "Traffic Cone",
    "object--traffic-light--cyclists": "Traffic Light - Cyclists",
    "object--traffic-light--general-horizontal": "Traffic Light - General (Horizontal)",
    "object--traffic-light--general-single": "Traffic Light - General (Single)",
    "object--traffic-light--general-upright": "Traffic Light - General (Upright)",
    "object--traffic-light--other": "Traffic Light - Other",
    "object--traffic-light--pedestrians": "Traffic Light - Pedestrians",
    "object--trash-can": "Trash Can",
    "object--water-valve": "Water Valve"
};
